const STATE = {
  accessToken: '',
  user: {},
  isDarkMode: false,
  residentsData: [],
  successMessage: '',
  failureMessage: '',
  nav: null,
  selectedResident: null,
  localDbUser: null,
  signalSyncArray: [],
  residentSignalSyncArray: [],
  alertsArray: [],
  numberOfAlerts: 0,
  localResidentList: [],
  loginNav: null,
  isFahrenheit: true,
  lastSynced: '',
  loginTime: '',
  uploadImageSelected: -1,
  drawerNav: null,
  totalArrayCount: 0,
  tempResidentArray: [],
  heartHistoryArray: [],
  respiratoryHistoryArray: [],
  stressHistoryArray: [],
  tempHistoryArray: [],
  termsChecked: false,
  privacyChecked: false,
  userName: '',
  isGalen: true,
  observeListArray: [],
  usersListArray: [],
  customDataArray: [],
  userEmail: '',
  localReadAlertArray: [],
  selectedMacAddress: '',
  activeMacAddress: [],
  app_version_number_ios: '1.0',
  app_build_number_ios: '1.0.12',
  app_version_number_android: 1.0,
  app_build_number_android: 1.2,
  scannedUserArray: [],
  selectedSensorMacAddress: '',
  selectedSensorUserId: '',
  totalUnreadAlert: 0,
  enableNotification: false,
  notificationType: {},
  selectedUser: {label: 'All', value: 'All'},
  selectedFriendlyName: {label: 'All', value: 'All'},
  filteredArray: [],
  alertsCountArray: [],
  filterApplied: false,
  statsTheme: 'H-R View',
  currentActiveIndex: 0,
  allUsersArray: [],
  currentlySelected: '',
  isPrefEnabled: true,
  subsciptionsArrayList: [],
  version: '2.1.26',
  letInterval: 120,
  bufferValue: 5,
  reportsUpdatedAt: '',
  reportsArray: [],
  selectedPracticeId: '',
  lastUserData: null,
  keychainEmail: '',
  keychainPassword: '',
  showFloatingWindow: false,
  floatingWindowData: null,
};

export default STATE;
